### ISSUE TITLE
Please build a new release which supports SonarQube 7.4

### ISSUE THREAD

**Issue by ws11606** [lg2de/sonar-scm-tfvc#47]
Can someone please build a new release which supports SonarQube 7.4? The latest release 2.1.2 does not support SonarQube 7.4. I tried to compile latest master branch source files sonar-scm-tfvc-master/pom.xml with "mvn package" but getting this error:
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.3.2:exec (msbuild-build) on project SonarTfsAnnotate: The parameters 'executable' for goal org.codehaus.mojo:exec-maven-plugin:1.3.2:exec are missing or invalid -> [Help 1]

If I compile sonar-scm-tfvc-master\sonar-scm-tfvc-plugin\pom.xml, then I get this error:
[ERROR] Failed to execute goal on project sonar-scm-tfvc-plugin: Could not resolve dependencies for project org.sonarsource.tfvc:sonar-scm-tfvc-plugin:sonar-plugin:2.2-SNAPSHOT: Could not find artifact org.sonarsource.tfvc:SonarTfsAnnotate:zip:2.2-SNAPSHOT -> [Help 1]

Can someone help me? Thx.

**Comment by michha** [comment]
This is a duplicate of #45 and #46

**Comment by ws11606** [comment]
Hi michha,
You are correct in that a fix has been added to resolve this but there has been no new releases since 2.1.2. Can someone build latest source code and publish new release? Thx.
https://github.com/SonarQubeCommunity/sonar-scm-tfvc/releases

**Comment by dbolkensteyn** [comment]
Regarding the build error, you'll need to set the `MSBUILD_PATH` environment to point to `msbuild.exe`, similarly as to what is done in the AppVeyor build: https://github.com/SonarQubeCommunity/sonar-scm-tfvc/blob/master/appveyor.yml#L14

Why is that so?
1. This project contains both Java and C# code. The Java bits is built with Maven, and the C# bits by MSBuild.
2. However, the overall build is orchestrated by Maven. This means that MSBuild will be invoked by Maven. This is declared in this file: https://github.com/SonarQubeCommunity/sonar-scm-tfvc/blob/master/SonarTfsAnnotate/pom.xml#L30

If the `MSBUILD_PATH` environment variable is not set, Maven will substitute it with the empty string, which ultimately will lead to the invalid `executable` error message that you are getting @ws11606 .

Hope this helps.

**Comment by ws11606** [comment]
Thanks @dbolkensteyn for your help. After setting set MSBUILD_PATH="F:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe", I was able to successfully build the Maven pom.xml which created sonar-scm-tfvc-plugin-2.2-SNAPSHOT.jar. Unfortunately, I can't test it until I upgrade dev SonarQube environment to 7.4 which is currently 6.5 and uses old SQL server 2012. Need to migrate to SQL server 2016. I had upgraded Prod SonarQube to ver 6.7.6 which uses SQL server 2016. Will get back to you.

**Comment by psyvision** [comment]
@ws11606 have you managed to test this yet?  Did you make any code changes (i.e. the open PR for 7.3 compatibility) or just compile `master` ?

**Comment by ws11606** [comment]
Hi @psyvision 
I haven't had chance to test it. I'm still waiting for SQL server 2016 for Dev SQ environment. I need this ASAP from SQL team because all I have now is Prod SQ... :( Will post when I've tested. So right now, I only have the master branch compiled .jar file.

**Comment by psyvision** [comment]
Thanks @ws11606 - I've got 7.5 up and running now and have a MSBuild/Maven environment so I should be able to get this compiled and give it a test pretty quick.

**Comment by ManojCN** [comment]
Hi All, 
Can someone build latest source code and publish new [release](https://github.com/SonarQubeCommunity/sonar-scm-tfvc/releases)? or is it done?

BR//Manoj C N

**Comment by ws11606** [comment]
I finally acquired SQL server 2016 for testing SQ 7.5 TFVC plugin.
After copying newly compiled sonar-scm-tfvc-plugin-2.2-SNAPSHOT.jar to the plugin folder and starting SQ, it failed. Hope someone can help. Here's log:

2019.01.25 18:24:15 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin TFVC / 2.2-SNAPSHOT / 0
2019.01.25 18:24:15 WARN  web[][o.s.c.p.PluginLoader] API compatibility mode is no longer supported. In case of error, plugin TFVC [scmtfvc] should package its dependencies.
2019.01.25 18:24:16 INFO  web[][o.s.s.p.d.m.c.MssqlCharsetHandler] Verify that database collation is case-sensitive and accent-sensitive
2019.01.25 18:24:16 INFO  web[][o.s.s.p.w.MasterServletFilter] Initializing servlet filter org.sonar.server.ws.WebServiceFilter@7821e4b [pattern=UrlPattern{inclusions=[/api/system/migrate_db.*, ...], exclusions=[/api/properties*, ...]}]
2019.01.25 18:24:16 INFO  web[][o.s.s.a.EmbeddedTomcat] HTTP connector enabled on port 9090
2019.01.25 18:24:17 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
java.lang.IllegalStateException: Fail to load plugin TFVC [scmtfvc]
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:82)
	at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:586)
	at org.sonar.server.platform.Platform.start(Platform.java:211)
	at org.sonar.server.platform.Platform.startLevel34Containers(Platform.java:185)
	at org.sonar.server.platform.Platform.access$500(Platform.java:46)
	at org.sonar.server.platform.Platform$1.lambda$doRun$0(Platform.java:119)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:371)
	at org.sonar.server.platform.Platform$1.doRun(Platform.java:119)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:355)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: com/google/common/collect/ImmutableList
	at org.sonar.plugins.scm.tfs.TfsPlugin.getExtensions(TfsPlugin.java:18)
	at org.sonar.api.SonarPlugin.define(SonarPlugin.java:51)
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:72)
	... 9 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.ImmutableList
	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
	... 12 common frames omitted
2019.01.25 18:24:17 INFO  web[][o.s.p.StopWatcher] Stopping process

**Comment by TomaszDom** [comment]
So is anybody any closer to making this work?

**Comment by TomaszDom** [comment]
What a nightmare to build. I've attached a build of https://github.com/SonarQubeCommunity/sonar-scm-tfvc/pull/44/commits/f1342cfaeb27076ea8e3b6234942328b7b45dc35 which supposedly should work better with later versions of SonarQube.

I DID NOT TEST THIS.

[sonar-scm-tfvc-plugin-2.2-SNAPSHOT.jar.zip](https://github.com/SonarQubeCommunity/sonar-scm-tfvc/files/2854656/sonar-scm-tfvc-plugin-2.2-SNAPSHOT.jar.zip)

**Comment by wilsade** [comment]
Hi @TomaszDom.
I tested it.
I've got error: System.IO.FileNotFoundException, Microsoft.TeamFoundation.Client, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.

Can you, please, recompile with version 15.0 (compatible with Visual Studio 2017).
Thanks

**Comment by thelittleflea** [comment]
Hi @TomaszDom, @wilsade,
I've done something a little ugly, but it works for me. I just unzip 2.1.6 version in order to get SonarTfsAnnotate.exe. Then I add it manualy into your 2.2-SNAPSHOT build.
It works for me with TFS2015.4 and Sonarqube 7.6.

I hope this could help.

[sonar-scm-tfvc-plugin-2.2-SNAPSHOT.jar.zip](https://github.com/SonarQubeCommunity/sonar-scm-tfvc/files/2855508/sonar-scm-tfvc-plugin-2.2-SNAPSHOT.jar.zip)

**Comment by wilsade** [comment]
Hi @thelittleflea .
My issue is that I only have VS2017 installed.
I'm afraid this workaround wont work for me.

Regards,

**Comment by TomaszDom** [comment]
@wilsade install https://visualstudiogallery.msdn.microsoft.com/3278bfa7-64a7-4a75-b0da-ec4ccb8d21b6/file/116382/1/tfs_ObjectModel.exe on the machine where you run MSBuild and report back.

**Comment by TomaszDom** [comment]
@thelittleflea My package is a clean successful rebuild of the mentioned branch, there is no need for ugliness I think. I'm successfully scanning VS2015 Update 3 projects, no issues so far.

**Comment by thelittleflea** [comment]
What is your Tfs assembly version ? You can take a look into your Tfs Agent folder (ie: .. Tfs\agent-1\Agent\Worker)
First I build the exe file using 15.0.0.0 version of Tfs assembly. But it dosn't work for me (TFS2015 14.0.0.0)
Here is the file if you want to test.
[SonarTfsAnnotate.zip](https://github.com/SonarQubeCommunity/sonar-scm-tfvc/files/2855609/SonarTfsAnnotate.zip)

**Comment by thelittleflea** [comment]
@TomaszDom 
Sorry for the Uglyness. But i had the same exception as @wilsade. Strange

**Comment by TomaszDom** [comment]
@wilsade I have TFS2017.3 on-premises, but the difference is that it has been upgraded on the same machine from TFS2008 -> 2010 -> 2012 -> 2013 -> 2015 -> 2017, so I probably have all the legacy libraries needed to make it work...

**Comment by psyvision** [comment]
I think the problem is you'll use the TFS binaries from a particular version and it won't work with another TFS version.

It may be further problematic with Git in TFS as opposed to the TFVC that this was originally designed for?

**Comment by ws11606** [comment]
Thanks @TomaszDom . I tried your build and it worked for me on SQ 7.6. Maybe I previously incorrectly built it.

FYI, there's a newer version of Team Foundation Server 2013 Update 5 Object Model Installer at:
https://marketplace.visualstudio.com/items?itemName=VSCSReleases.TeamFoundationServer2013Update5ObjectModelInstalle

Unfortunately, TFVC changes at the source file level no longer shows who made the changes but shows date and TFS ChangeSet ID like this:
![image](https://user-images.githubusercontent.com/25942824/52681003-4028fc00-2eef-11e9-9c22-5a61dcad082c.png)

It used to show this:
![image](https://user-images.githubusercontent.com/25942824/52681019-4fa84500-2eef-11e9-9f31-aac11d04bc3c.png)

It's still a great plug-in tool though so I'm grateful to all who contributed.

Now I need to test with TFS 2018 Update 3.2 since we're planning to upgrade TFS soon. Will report back.

**Comment by colin-mueller-sonarsource** [comment]
Just a reminder to all -- this repo is in the SonarQubeCommunity organization and has no maintainer, so no PRs are likely to be merged. If anybody is interested in formally adopting / taking over this plugin and making new releases, drop a note at https://community.sonarsource.com

**Comment by SirBisgaard** [comment]
Hi,
I installed the snapshot on our environment.
We are currently running the following: SQ 7.6, TFS 2018 and SqlServer 2017.

The snapshot works and does not crash like the latest release. But have the same experience as @ws11606 

@colin-mueller-sonarsource Does this mean that SonarSource is not planning to support this plugin in the future? 
- Not that I'm complaining now that microsoft is heavily adopting Git.

**Comment by colin-mueller-sonarsource** [comment]
Hey @SirBisgaard,

Correct, this plugin has not been maintained, supported, or developed by SonarSource in a few years.

Colin

**Comment by SirBisgaard** [comment]
Hey Colin,
This might not be relevant here. I have compiled both projects of the plugin, and everything is working as expected. (That it can scrape changeset id, username, unix time) So the problem might be in SonarQube itself, or is the API changed for the plugin interface?

**Comment by lg2de** [comment]
The new release 2.2 is working fine with SQ 7.4 to 7.9.
